name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Fetch latest versions
        id: update
        run: make update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            branch: update-coredns
            commit-message: Update Dependencies
            title: Update CoreDNS Versions
            delete-branch: true
